name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest  # Change from ubuntu-24.04 to latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Ensure this version exists

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Ensure this version exists

      - name: Install dependencies (Python)
        run: |
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Install dependencies (Node.js)
        run: |
          if [ -f "package.json" ]; then npm install; fi

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        run: snyk test --all-projects --detection-depth=3
