name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        run: snyk test --all-projects

      - name: Monitor Project
        run: snyk monitor
